repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8  # pin to a released tag
    hooks:
      - id: ruff
        args: [--fix]        # auto-fix where safe
      - id: ruff-format      # ruff's formatter (PEP 8/Black-compatible)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
