[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{PACKAGE_NAME}"
version = "0.1.0"
description = "A brief description of the package."
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = "GPL-3.0"
readme = "README.md"
requires = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPL-3.0)",
    "Operating System :: OS Independent"
]
