name: Tests

on:
  push:
  pull_request:

# Cancel older in-progress runs for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: py${{ matrix.python-version }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            requirements-test.txt
            requirements-*.txt

      - name: Install dependencies
        shell: bash  # keeps commands identical across OSes
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          # If your package is installable (setup.cfg/setup.py/pyproject with setuptools), this will succeed; otherwise it’s ignored.
          pip install -e . || true
          pip install pytest

      - name: Run tests
        run: pytest -q
